package com.marmatsan.figmaDesignSync.domain.model.writer

/** Typed repository configuration consumed by the portable Figma writer. */
data class FigmaWriterProjectConfig(
    val metadataPageId: String,
    val metadataNamespace: String,
    val figmaFileKey: String,
    val projectDisplayName: String,
    val mcpClientName: String,
    val ciDocumentationPageId: String,
    val ciNodeComponentId: String,
    val ciIconComponentSetId: String,
    val ciVariableCollectionName: String,
    val ciVariableModeNames: List<String>,
    val ciNodeInstanceName: String,
    val ciIconInstanceName: String,
    val ciIconEnvironmentProperty: String,
    val ciIconEnvironments: List<String>,
    val ciConnectorName: String,
    val ciConnectorLabelName: String,
    val ciConnectorTemplateSectionId: String,
    val ciNodeProps: Map<String, String>,
    val versionsCollectionName: String,
    val versionAliasModeName: String,
    val versionNumberModeName: String,
    val outlineColorVariableName: String,
    val dependencyVersionComponentId: String,
    val dependencyVersionInstanceNames: List<String>,
    val dependencyVersionProps: Map<String, String>,
    val parentSectionSiblingGap: Int,
    val parentSectionNodeIds: List<String>,
    val sectionSiblingGap: Int,
    val treeNodeComponentIds: Map<String, String>,
    val connectorTemplateName: String,
    val headerInstanceName: String,
    val headerLinkPropertyName: String,
    val githubMainBlobUrl: String,
    val githubMainTreeUrl: String,
    val ciConfigurationModelName: String,
    val ciPipelineName: String,
    val figmaPipelineName: String,
    val teamCitySource: String,
    val topologySource: String,
    val windowsRuntimeSource: String,
    val windowsRuntimeRunbookSource: String,
    val visualContractSource: String,
    val branchProtectionSource: String,
    val officialSyncSource: String,
    val officialDesignModelPath: String,
    val repositoryRootRelativeToTools: String,
    val changeImpactPolicyRelativeToRepository: String,
    val headerSectionTargets: List<FigmaHeaderSectionTarget>,
    val versionSectionTargets: Map<String, FigmaVersionSectionTarget>,
    val treeNodeProps: Map<String, String>,
    val artifactProps: Map<String, String>,
    val artifactsBundleProps: Map<String, String>,
    val artifactInstanceName: String,
    val artifactsBundleInstanceName: String,
    val usageChipComponentSetId: String,
    val usageChipInstanceName: String,
    val toolArtifactUsageInstanceName: String,
    val toolArtifactUsageProps: Map<String, String>,
    val usageChipProps: Map<String, String>,
    val usageChipKinds: Map<String, String>,
    val catalogTreeTargets: List<FigmaCatalogTreeTargetConfig>,
    val ciVisualTargetNames: List<String>,
    val defaultFixtureTargets: Map<String, String>
)
