# Versions used to compile and test the Gradle convention plugins.
androidGradlePluginVersion=9.2.1
dokkaPluginVersion=2.2.0
kotlinVersion=2.4.0
kotestLibraryVersion=6.2.1
mockkLibraryVersion=1.14.11
protobufPluginVersion=0.10.0
unitTestDslLibraryVersion=0.1.0-SNAPSHOT
