activityComposeVersion=1.12.2
androidCoroutinesVersion=1.10.2
applicationVersion=8.13.2
assertkVersion=0.28.1
composeBomVersion=2025.12.01
composeCompilerVersion=1.5.15
coreKtxVersion=1.17.0
coreSplashscreenVersion=1.2.0
datastoreVersion=1.2.0
figmaCodeConnectPluginVersion=1.2.8
figmaCodeConnectLibraryVersion=1.1.3
junit5BomVersion=6.0.1
junit5PluginVersion=1.14.0.0
kotlinInjectVersion=0.8.0
kotlinVersion=2.3.0
kspVersion=2.3.4
landscapistVersion=2.3.6
lifecycleVersion=2.10.0
mockkVersion=1.14.7
navigationComposeVersion=2.9.6
protobufGradlePluginVersion=0.9.6
protobufLibraryVersion=4.33.2
protobufPluginVersion=0.9.6
serializationVersion=1.7.1