# Reusable project-config build dependencies.

kotlinVersion=2.4.0
dokkaPluginVersion=2.2.0
dependencyCatalogVersion=0.1.0-SNAPSHOT
figmaDocumentationSyncVersion=0.1.0-SNAPSHOT
kotestLibraryVersion=6.2.1
projectConfigVersion=0.1.0-SNAPSHOT
unitTestDslLibraryVersion=0.1.0-SNAPSHOT
