/**
 * Figma MCP script for build-logic/figmaDesignSync/docs/figma-trunk-sync.md.
 *
 * Execute the generated, untracked sync-trunk-design-model.mcp.js with the Figma MCP use_figma tool.
 * Replace DESIGN_MODEL in the generated JavaScript with the JSON generated by
 * ./gradlew.bat generateFigmaDesignModel before running it.
 */
import { createFigmaDesignModelSync } from "./create-figma-design-model-sync";
import type { DesignModel } from "../domain/design-model";

export async function main(designModel: DesignModel | undefined) {
  return createFigmaDesignModelSync()(designModel);
}
