/**
 * Figma MCP script for build-logic/figmaDesignSync/docs/figma-develop-sync.md.
 *
 * Execute this with the Figma MCP use_figma tool. Replace DESIGN_MODEL with the
 * JSON generated by ./gradlew.bat generateFigmaDesignModel before running it.
 */
const DESIGN_MODEL = undefined;

const METADATA_PAGE_ID = "62934:908";
const METADATA_NAMESPACE = "water_my_plants_sync";
const VERSIONS_COLLECTION_NAME = "build-logic\\versions.properties";
const VERSION_ALIAS_MODE_NAME = "Version alias";
const VERSION_NUMBER_MODE_NAME = "Version number";
const PROJECT_VERSION_COMPONENT_ID = "63075:591";
const TREE_NODE_COMPONENT_IDS = {
  Library: "63069:681",
  Plugin: "63069:694",
};
const CONNECTOR_TEMPLATE_NAME = "simple-solid_arrow";

const VERSION_SECTION_TARGETS = {
  "Main project dependencies": {
    parentNodeId: "63075:634",
    variableFolder: "Main project dependencies",
  },
  Libraries: {
    parentNodeId: "63075:644",
    variableFolder: "Libraries",
  },
  Plugins: {
    parentNodeId: "63075:804",
    variableFolder: "Plugins",
  },
};

const TREE_NODE_PROPS = {
  libraryGroup: "Library group#1345:12",
  pluginId: "Plugin ID#1345:16",
  showPluginVersion: "Show plugin version#58719:0",
  showArtifacts: "Show artifacts#63079:0",
  pluginVersion: "Plugin version#63081:2",
  showConsumerModule: "Show consumer module#63085:0",
  showIsGradleConventionPlugin: "Show is a gradle convention plugin#63112:4",
  type: "Type",
};
const ARTIFACT_PROPS = {
  showConsumerModules: "Show consumer modules#63086:1",
};
const ARTIFACTS_BUNDLE_PROPS = {
  showConsumerModules: "Show consumer modules#63107:0",
};
const ARTIFACT_INSTANCE_NAME = ".artifact";
const ARTIFACTS_BUNDLE_INSTANCE_NAME = ".artifacts bundle";
const MODULE_INSTANCE_NAME = ".module";
const MODULE_PROPS = {
  name: "name",
  size: "size",
};
const SMALL_MODULE_SIZE = "small";

const CATALOG_TREE_TARGETS = [
  {
    name: "waterMyPlants.libraries",
    sectionNodeId: "63069:629",
    type: "Library",
    nodes: (designModel) => designModel.content?.catalogs?.waterMyPlants?.libraries,
  },
  {
    name: "waterMyPlants.plugins",
    sectionNodeId: "63069:594",
    type: "Plugin",
    nodes: (designModel) => designModel.content?.catalogs?.waterMyPlants?.plugins,
  },
  {
    name: "buildLogic.libraries",
    sectionNodeId: "63099:951",
    type: "Library",
    nodes: (designModel) => designModel.content?.catalogs?.buildLogic?.libraries,
  },
  {
    name: "buildLogic.plugins",
    sectionNodeId: "63100:2952",
    type: "Plugin",
    nodes: (designModel) => designModel.content?.catalogs?.buildLogic?.plugins,
  },
];

async function main(designModel) {
  if (!designModel) {
    throw new Error("Replace DESIGN_MODEL with build/reports/figma-sync/design-model.json.");
  }

  const versionSections = requireVersionSections(designModel);
  const collection = await requireVariableCollection(VERSIONS_COLLECTION_NAME);
  const versionAliasModeId = requireModeId(collection, VERSION_ALIAS_MODE_NAME);
  const versionNumberModeId = requireModeId(collection, VERSION_NUMBER_MODE_NAME);
  const projectVersionComponent = await requireComponent(PROJECT_VERSION_COMPONENT_ID);

  const variables = await loadVariablesByVersionKey(collection);
  const mutatedNodeIds = [];
  const createdVariables = [];
  const createdInstances = [];
  const updatedVersions = [];
  const updatedCatalogNodes = [];
  const createdCatalogNodes = [];
  const createdCatalogConnectors = [];

  for (const section of versionSections) {
    const target = VERSION_SECTION_TARGETS[section.name];
    if (!target) {
      throw new Error(`No Figma target configured for version section '${section.name}'.`);
    }

    const parent = await requireFrame(target.parentNodeId);
    const entries = Object.entries(section.versions);

    for (const [versionKey, versionNumber] of entries) {
      let variable = variables.get(versionKey);

      if (!variable) {
        variable = figma.variables.createVariable(
          `${target.variableFolder}/${versionKey}`,
          collection,
          "STRING"
        );
        variable.scopes = ["TEXT_CONTENT"];
        variables.set(versionKey, variable);
        createdVariables.push(variable.name);
      }

      variable.setValueForMode(versionAliasModeId, versionKey);
      variable.setValueForMode(versionNumberModeId, versionNumber);
      updatedVersions.push(versionKey);

      const existingInstance = findProjectVersionInstance(parent, versionKey);
      if (!existingInstance) {
        const instance = projectVersionComponent.createInstance();
        const position = nextProjectVersionPosition(parent);

        parent.appendChild(instance);
        instance.x = position.x;
        instance.y = position.y;
        bindProjectVersionInstance(instance, variable);

        mutatedNodeIds.push(instance.id);
        createdInstances.push(versionKey);
      }

      mutatedNodeIds.push(variable.id);
    }
  }

  const catalogSyncResult = await syncCatalogTrees(designModel);
  updatedCatalogNodes.push(...catalogSyncResult.updatedCatalogNodes);
  createdCatalogNodes.push(...catalogSyncResult.createdCatalogNodes);
  createdCatalogConnectors.push(...catalogSyncResult.createdCatalogConnectors);
  mutatedNodeIds.push(...catalogSyncResult.mutatedNodeIds);

  const page = await requirePage(METADATA_PAGE_ID);
  await figma.setCurrentPageAsync(page);
  writeMetadata(page, designModel);
  mutatedNodeIds.push(page.id);

  return {
    updatedVersions,
    createdVariables,
    createdInstances,
    updatedCatalogNodes,
    createdCatalogNodes,
    createdCatalogConnectors,
    metadata: {
      pageId: page.id,
      namespace: METADATA_NAMESPACE,
      gitSha: page.getSharedPluginData(METADATA_NAMESPACE, "gitSha"),
      modelHash: page.getSharedPluginData(METADATA_NAMESPACE, "modelHash"),
    },
    mutatedNodeIds: [...new Set(mutatedNodeIds)],
  };
}

function requireVersionSections(designModel) {
  const sections = designModel.content?.versionSections;
  if (!Array.isArray(sections) || sections.length === 0) {
    throw new Error("designModel.content.versionSections is required for visual version sync.");
  }
  return sections;
}

async function requireVariableCollection(name) {
  const collections = await figma.variables.getLocalVariableCollectionsAsync();
  const collection = collections.find((candidate) => candidate.name === name);
  if (!collection) {
    throw new Error(`Variable collection '${name}' was not found.`);
  }
  return collection;
}

function requireModeId(collection, modeName) {
  const mode = collection.modes.find((candidate) => candidate.name === modeName);
  if (!mode) {
    throw new Error(`Mode '${modeName}' was not found in '${collection.name}'.`);
  }
  return mode.modeId;
}

async function loadVariablesByVersionKey(collection) {
  const variables = new Map();

  for (const variableId of collection.variableIds) {
    const variable = await figma.variables.getVariableByIdAsync(variableId);
    if (!variable) continue;

    const versionKey = variable.name.split("/").at(-1);
    variables.set(versionKey, variable);
  }

  return variables;
}

async function requireComponent(nodeId) {
  const node = await figma.getNodeByIdAsync(nodeId);
  if (!node || node.type !== "COMPONENT") {
    throw new Error(`Expected '${nodeId}' to be a COMPONENT.`);
  }
  return node;
}

async function requireFrame(nodeId) {
  const node = await figma.getNodeByIdAsync(nodeId);
  if (!node || node.type !== "FRAME") {
    throw new Error(`Expected '${nodeId}' to be a FRAME.`);
  }
  return node;
}

async function requirePage(nodeId) {
  const node = await figma.getNodeByIdAsync(nodeId);
  if (!node || node.type !== "PAGE") {
    throw new Error(`Expected '${nodeId}' to be a PAGE.`);
  }
  return node;
}

function findProjectVersionInstance(parent, versionKey) {
  return parent.children.find((child) => {
    if (child.type !== "INSTANCE" || child.name !== ".project version") return false;
    return collectText(child).includes(versionKey);
  });
}

function collectText(node) {
  const text = [];

  if ("characters" in node) {
    text.push(node.characters);
  }

  if ("children" in node) {
    for (const child of node.children) {
      text.push(...collectText(child));
    }
  }

  return text;
}

function nextProjectVersionPosition(parent) {
  const instances = parent.children
    .filter((child) => child.type === "INSTANCE" && child.name === ".project version")
    .sort((first, second) => first.y - second.y || first.x - second.x);

  if (instances.length === 0) {
    return { x: 0, y: 0 };
  }

  const columnXs = [...new Set(instances.map((instance) => Math.round(instance.x)))]
    .sort((first, second) => first - second)
    .slice(0, 2);

  if (columnXs.length === 1) {
    columnXs.push(columnXs[0] + Math.round(instances[0].width) + 64);
  }

  const nextColumnIndex = instances.length % columnXs.length;
  const columnInstances = instances.filter((instance) => Math.round(instance.x) === columnXs[nextColumnIndex]);
  const lastInColumn = columnInstances.at(-1);
  const rowGap = 64;

  return {
    x: columnXs[nextColumnIndex],
    y: lastInColumn ? lastInColumn.y + lastInColumn.height + rowGap : 0,
  };
}

function bindProjectVersionInstance(instance, variable) {
  const alias = figma.variables.createVariableAlias(variable);

  instance.setProperties({
    "Version alias#63075:0": alias,
    "Version number#63075:1": alias,
  });
}

async function syncCatalogTrees(designModel) {
  const updatedCatalogNodes = [];
  const createdCatalogNodes = [];
  const createdCatalogConnectors = [];
  const mutatedNodeIds = [];
  const componentCache = new Map();

  for (const target of CATALOG_TREE_TARGETS) {
    const modelNodes = target.nodes(designModel);
    if (!Array.isArray(modelNodes)) {
      throw new Error(`designModel.content.catalogs.${target.name} is required for catalog tree sync.`);
    }

    const expectedNodes = flattenCatalogNodes(modelNodes, target.type);
    requireUniqueLabels(target, expectedNodes);

    const section = await requireSection(target.sectionNodeId);
    const instancesByLabel = collectTreeNodeInstancesByLabel(section, target.type);
    const connectors = collectTreeConnectors(section);

    for (const node of expectedNodes) {
      if (instancesByLabel.has(node.label)) continue;

      const instance = await createMissingTreeNode(
        target,
        section,
        node,
        instancesByLabel,
        componentCache,
        mutatedNodeIds
      );
      instancesByLabel.set(node.label, instance);
      createdCatalogNodes.push(`${target.name}/${node.path.join("/")}`);
    }

    for (const node of expectedNodes) {
      const instance = instancesByLabel.get(node.label);
      if (node.type === "Library") {
        await updateLibraryTreeNode(instance, node, mutatedNodeIds);
      } else {
        await updatePluginTreeNode(instance, node, mutatedNodeIds);
      }
      updatedCatalogNodes.push(`${target.name}/${node.path.join("/")}`);
    }

    for (const node of expectedNodes.filter((candidate) => candidate.parentPath.length > 0)) {
      const parentLabel = node.parentPath[node.parentPath.length - 1];
      const parentInstance = instancesByLabel.get(parentLabel);
      const childInstance = instancesByLabel.get(node.label);

      if (!parentInstance || !childInstance) {
        throw new Error(`Cannot create connector for ${target.name}/${node.path.join("/")}: parent or child is missing.`);
      }

      if (hasConnector(connectors, parentInstance.id, childInstance.id)) {
        continue;
      }

      const connector = createTreeConnector(section, parentInstance, childInstance);
      connectors.push(connector);
      mutatedNodeIds.push(connector.id);
      createdCatalogConnectors.push(`${target.name}/${node.parentPath.join("/")} -> ${node.path.join("/")}`);
    }
  }

  return {
    updatedCatalogNodes,
    createdCatalogNodes,
    createdCatalogConnectors,
    mutatedNodeIds,
  };
}

function flattenCatalogNodes(nodes, type, parentPath = []) {
  return nodes.flatMap((node) => {
    const label = type === "Library" ? node.group : node.id;
    const path = [...parentPath, label];
    const current = type === "Library"
      ? {
          type,
          label,
          parentPath,
          path,
          artifactsVisible: node.artifactsVisible,
          entries: node.entries || [],
          children: node.children || [],
        }
      : {
          type,
          label,
          parentPath,
          path,
          version: node.version,
          appliedToModules: node.appliedToModules || [],
          children: node.children || [],
        };

    return [
      current,
      ...flattenCatalogNodes(current.children, type, path),
    ];
  });
}

function requireUniqueLabels(target, nodes) {
  const labels = new Map();
  for (const node of nodes) {
    labels.set(node.label, (labels.get(node.label) || 0) + 1);
  }

  const duplicateLabels = [...labels.entries()]
    .filter(([, count]) => count > 1)
    .map(([label]) => label);

  if (duplicateLabels.length > 0) {
    throw new Error(
      `${target.name} contains duplicate labels (${duplicateLabels.join(", ")}). ` +
        "Catalog tree update-only sync needs stable Figma node path metadata before it can continue."
    );
  }
}

async function requireSection(nodeId) {
  const node = await figma.getNodeByIdAsync(nodeId);
  if (!node || node.type !== "SECTION") {
    throw new Error(`Expected '${nodeId}' to be a SECTION.`);
  }
  return node;
}

function collectTreeNodeInstancesByLabel(section, type) {
  const instances = section.findAllWithCriteria({ types: ["INSTANCE"] })
    .filter((instance) => getComponentPropertyValue(instance, TREE_NODE_PROPS.type) === type);
  const instancesByLabel = new Map();

  for (const instance of instances) {
    const label = type === "Library"
      ? getComponentPropertyValue(instance, TREE_NODE_PROPS.libraryGroup)
      : getComponentPropertyValue(instance, TREE_NODE_PROPS.pluginId);

    if (!label || label === "Library group" || label === "Plugin ID") continue;
    if (instancesByLabel.has(label)) {
      throw new Error(`Duplicate '${label}' ${type} tree node instances were found in section '${section.name}'.`);
    }
    instancesByLabel.set(label, instance);
  }

  return instancesByLabel;
}

function getComponentPropertyValue(instance, propertyName) {
  return instance.componentProperties?.[propertyName]?.value;
}

async function createMissingTreeNode(target, section, node, instancesByLabel, componentCache, mutatedNodeIds) {
  const container = requireTreeNodeContainer(section, node);
  const template = findTreeNodeTemplate(section, node);
  const instance = template
    ? template.clone()
    : (await requireTreeNodeComponent(node.type, componentCache)).createInstance();

  container.appendChild(instance);
  instance.name = ".tree node";

  const position = nextTreeNodePosition(container, node, instancesByLabel);
  instance.x = position.x;
  instance.y = position.y;

  if (node.type === "Library") {
    await updateLibraryTreeNode(instance, node, mutatedNodeIds);
  } else {
    await updatePluginTreeNode(instance, node, mutatedNodeIds);
  }

  mutatedNodeIds.push(instance.id);
  return instance;
}

function requireTreeNodeContainer(section, node) {
  const rootLabel = node.path[0];
  const existingContainer = section.children.find((child) => child.type === "SECTION" && child.name === rootLabel);

  if (existingContainer) {
    return existingContainer;
  }

  if (node.path.length > 1) {
    throw new Error(`Cannot create ${node.path.join("/")}: root section '${rootLabel}' is missing.`);
  }

  const newSection = figma.createSection();
  newSection.name = rootLabel;
  section.appendChild(newSection);

  const position = nextTopLevelSectionPosition(section);
  newSection.x = position.x;
  newSection.y = position.y;
  newSection.resizeWithoutConstraints(1200, 900);

  return newSection;
}

function nextTopLevelSectionPosition(section) {
  const sections = section.children
    .filter((child) => child.type === "SECTION")
    .sort((first, second) => first.y - second.y || first.x - second.x);

  if (sections.length === 0) {
    return { x: 100, y: 100 };
  }

  const last = sections[sections.length - 1];
  return {
    x: last.x + last.width + 100,
    y: last.y,
  };
}

function findTreeNodeTemplate(section, node) {
  const candidates = section.findAllWithCriteria({ types: ["INSTANCE"] })
    .filter((instance) => getComponentPropertyValue(instance, TREE_NODE_PROPS.type) === node.type);

  if (node.type === "Plugin") {
    const showPluginVersion = node.version?.visible === true && Boolean(node.version?.value);
    return candidates.find((instance) =>
      getComponentPropertyValue(instance, TREE_NODE_PROPS.showPluginVersion) === showPluginVersion
    ) || candidates[0];
  }

  const artifactNameCount = libraryArtifactNames(node.entries).length;
  const artifactVersionCount = libraryArtifactVersions(node.entries).length;
  return candidates.find((instance) =>
    countNamedTextNodes(instance, "artifact name") === artifactNameCount &&
      countNamedTextNodes(instance, "artifact version") === artifactVersionCount
  ) || candidates.find((instance) =>
    getComponentPropertyValue(instance, TREE_NODE_PROPS.showArtifacts) === (node.artifactsVisible && artifactNameCount > 0)
  ) || candidates[0];
}

function countNamedTextNodes(root, name) {
  return root.findAllWithCriteria({ types: ["TEXT"] })
    .filter((textNode) => textNode.name === name)
    .length;
}

async function requireTreeNodeComponent(type, componentCache) {
  if (componentCache.has(type)) {
    return componentCache.get(type);
  }

  const componentId = TREE_NODE_COMPONENT_IDS[type];
  const component = await requireComponent(componentId);
  componentCache.set(type, component);
  return component;
}

function nextTreeNodePosition(container, node, instancesByLabel) {
  if (node.parentPath.length > 0) {
    const parentLabel = node.parentPath[node.parentPath.length - 1];
    const parentInstance = instancesByLabel.get(parentLabel);
    if (parentInstance) {
      const siblingInstances = container.children
        .filter((child) => child.type === "INSTANCE" && child.id !== parentInstance.id)
        .sort((first, second) => first.y - second.y || first.x - second.x);
      const lastSibling = siblingInstances[siblingInstances.length - 1];
      const x = lastSibling
        ? lastSibling.x + lastSibling.width + 120
        : parentInstance.x;
      return {
        x,
        y: parentInstance.y + parentInstance.height + 180,
      };
    }
  }

  const instances = container.children
    .filter((child) => child.type === "INSTANCE")
    .sort((first, second) => first.y - second.y || first.x - second.x);

  if (instances.length === 0) {
    return { x: 100, y: 100 };
  }

  const last = instances[instances.length - 1];
  return {
    x: last.x + last.width + 120,
    y: last.y,
  };
}

function collectTreeConnectors(section) {
  return section.findAllWithCriteria({ types: ["CONNECTOR"] })
    .filter((connector) => connector.name === CONNECTOR_TEMPLATE_NAME);
}

function hasConnector(connectors, parentNodeId, childNodeId) {
  return connectors.some((connector) =>
    connector.connectorStart?.endpointNodeId === parentNodeId &&
      connector.connectorEnd?.endpointNodeId === childNodeId
  );
}

function createTreeConnector(section, parentInstance, childInstance) {
  const container = childInstance.parent && childInstance.parent.type === "SECTION"
    ? childInstance.parent
    : section;
  const template = findConnectorTemplate(container, section);
  const connector = template.clone();

  container.appendChild(connector);
  connector.name = CONNECTOR_TEMPLATE_NAME;
  connector.connectorStart = {
    endpointNodeId: parentInstance.id,
    magnet: "BOTTOM",
  };
  connector.connectorEnd = {
    endpointNodeId: childInstance.id,
    magnet: "TOP",
  };

  return connector;
}

function findConnectorTemplate(container, section) {
  const containerTemplate = container.findAllWithCriteria({ types: ["CONNECTOR"] })
    .find((connector) => connector.name === CONNECTOR_TEMPLATE_NAME);
  if (containerTemplate) {
    return containerTemplate;
  }

  const sectionTemplate = collectTreeConnectors(section)[0];
  if (sectionTemplate) {
    return sectionTemplate;
  }

  throw new Error(`No '${CONNECTOR_TEMPLATE_NAME}' connector template was found in section '${section.name}'.`);
}

async function updateLibraryTreeNode(instance, node, mutatedNodeIds) {
  const artifacts = libraryArtifacts(node.entries);
  const bundles = libraryBundles(node.entries);
  const artifactNames = artifacts.map((artifact) => artifact.name);
  const artifactVersions = libraryArtifactVersions(node.entries);
  const requiredByModules = sortedUnique([
    ...artifacts.flatMap((artifact) => artifact.requiredByModules),
    ...bundles.flatMap((bundle) => bundle.requiredByModules),
  ]);

  instance.setProperties({
    [TREE_NODE_PROPS.libraryGroup]: node.label,
    [TREE_NODE_PROPS.showArtifacts]: node.artifactsVisible && artifactNames.length > 0,
    [TREE_NODE_PROPS.showConsumerModule]: requiredByModules.length > 0,
    [TREE_NODE_PROPS.type]: "Library",
  });
  mutatedNodeIds.push(instance.id);

  await updateNamedTextNodes(instance, "Library group", [node.label], mutatedNodeIds);
  await updateNamedTextNodes(instance, "artifact name", artifactNames, mutatedNodeIds);
  await updateNamedTextNodes(instance, "artifact version", artifactVersions, mutatedNodeIds);
  await updateLibraryArtifactConsumerModules(instance, artifacts, mutatedNodeIds);
  await updateLibraryBundleConsumerModules(instance, bundles, mutatedNodeIds);
}

async function updatePluginTreeNode(instance, node, mutatedNodeIds) {
  const versionValue = node.version?.visible && node.version?.value
    ? node.version.value
    : "Plugin version";
  const appliedToModules = sortedUnique(node.appliedToModules || []);

  instance.setProperties({
    [TREE_NODE_PROPS.pluginId]: node.label,
    [TREE_NODE_PROPS.pluginVersion]: versionValue,
    [TREE_NODE_PROPS.showPluginVersion]: node.version?.visible === true && Boolean(node.version?.value),
    [TREE_NODE_PROPS.showConsumerModule]: appliedToModules.length > 0,
    [TREE_NODE_PROPS.type]: "Plugin",
  });
  mutatedNodeIds.push(instance.id);

  await updateConsumerModuleInstances(instance, "Applied by", appliedToModules, mutatedNodeIds);
}

function libraryArtifactNames(entries) {
  return libraryArtifacts(entries).map((artifact) => artifact.name);
}

function libraryArtifacts(entries) {
  return entries.flatMap((entry) => {
    if (entry.type === "artifact") {
      const requiredByModules = sortedUnique(entry.requiredByModules || []);
      return [{ name: entry.artifact, requiredByModules }];
    }
    if (entry.type === "bundle") {
      return (entry.artifacts || []).map((artifact) => ({ name: artifact, requiredByModules: [] }));
    }
    throw new Error(`Unsupported library catalog entry type '${entry.type}'.`);
  });
}

function libraryBundles(entries) {
  return entries
    .filter((entry) => entry.type === "bundle")
    .map((entry) => ({
      alias: entry.alias,
      requiredByModules: sortedUnique(entry.requiredByModules || []),
    }));
}

function libraryArtifactVersions(entries) {
  return entries.flatMap((entry) => {
    const version = entry.version;
    if (!version?.visible || !version.value) return [];
    if (entry.type === "artifact") return [version.value];
    if (entry.type === "bundle") return (entry.artifacts || []).map(() => version.value);
    throw new Error(`Unsupported library catalog entry type '${entry.type}'.`);
  });
}

function sortedUnique(values) {
  return [...new Set(values)].sort();
}

async function updateNamedTextNodes(root, name, expectedValues, mutatedNodeIds) {
  const textNodes = root.findAllWithCriteria({ types: ["TEXT"] })
    .filter((textNode) => textNode.name === name);

  if (textNodes.length !== expectedValues.length) {
    throw new Error(
      `Tree node '${root.id}' expected ${expectedValues.length} '${name}' text nodes, found ${textNodes.length}. ` +
        "Run the create-missing catalog tree phase before writing metadata."
    );
  }

  for (let index = 0; index < expectedValues.length; index += 1) {
    const textNode = textNodes[index];
    const nextValue = expectedValues[index];
    if (textNode.characters === nextValue) continue;

    await loadTextNodeFonts(textNode);
    textNode.characters = nextValue;
    mutatedNodeIds.push(textNode.id);
  }
}

async function updateLibraryArtifactConsumerModules(root, artifacts, mutatedNodeIds) {
  const artifactInstances = root.findAllWithCriteria({ types: ["INSTANCE"] })
    .filter((candidate) => candidate.name === ARTIFACT_INSTANCE_NAME);

  if (artifactInstances.length < artifacts.length) {
    throw new Error(
      `Tree node '${root.id}' expected at least ${artifacts.length} '${ARTIFACT_INSTANCE_NAME}' instances, ` +
        `found ${artifactInstances.length}. Update the .tree node component structure before writing metadata.`
    );
  }

  for (let index = 0; index < artifacts.length; index += 1) {
    const artifactInstance = artifactInstances[index];
    const artifact = artifacts[index];
    artifactInstance.setProperties({
      [ARTIFACT_PROPS.showConsumerModules]: artifact.requiredByModules.length > 0,
    });
    mutatedNodeIds.push(artifactInstance.id);
    await updateConsumerModuleInstances(
      artifactInstance,
      "Required by",
      artifact.requiredByModules,
      mutatedNodeIds
    );
  }
}

async function updateLibraryBundleConsumerModules(root, bundles, mutatedNodeIds) {
  const bundleInstances = root.findAllWithCriteria({ types: ["INSTANCE"] })
    .filter((candidate) => candidate.name === ARTIFACTS_BUNDLE_INSTANCE_NAME);

  if (bundleInstances.length < bundles.length) {
    throw new Error(
      `Tree node '${root.id}' expected at least ${bundles.length} '${ARTIFACTS_BUNDLE_INSTANCE_NAME}' instances, ` +
        `found ${bundleInstances.length}. Update the .tree node component structure before writing metadata.`
    );
  }

  for (let index = 0; index < bundles.length; index += 1) {
    const bundleInstance = bundleInstances[index];
    const bundle = bundles[index];
    bundleInstance.setProperties({
      [ARTIFACTS_BUNDLE_PROPS.showConsumerModules]: bundle.requiredByModules.length > 0,
    });
    mutatedNodeIds.push(bundleInstance.id);
    await updateConsumerModuleInstances(
      bundleInstance,
      "Required by",
      bundle.requiredByModules,
      mutatedNodeIds,
      { excludeArtifactDescendants: true }
    );
  }
}

async function updateConsumerModuleInstances(root, heading, modules, mutatedNodeIds, options = {}) {
  if (modules.length > 0) {
    requireConsumerModuleHeading(root, heading);
  }

  const moduleInstances = root.findAllWithCriteria({ types: ["INSTANCE"] })
    .filter((candidate) => candidate.name === MODULE_INSTANCE_NAME)
    .filter((candidate) => !options.excludeArtifactDescendants || !hasAncestorInstanceNamed(candidate, ARTIFACT_INSTANCE_NAME, root));

  if (moduleInstances.length < modules.length) {
    throw new Error(
      `Node '${root.id}' expected at least ${modules.length} '${MODULE_INSTANCE_NAME}' instances for '${heading}', ` +
        `found ${moduleInstances.length}. Update the .tree node component structure before writing metadata.`
    );
  }

  for (let index = 0; index < modules.length; index += 1) {
    const moduleInstance = moduleInstances[index];
    await setModuleInstance(moduleInstance, modules[index], mutatedNodeIds);
  }

  for (const moduleInstance of moduleInstances.slice(modules.length)) {
    if (moduleInstance.visible === false) continue;

    moduleInstance.visible = false;
    mutatedNodeIds.push(moduleInstance.id);
  }
}

function hasAncestorInstanceNamed(node, name, boundary) {
  let current = node.parent;
  while (current && current.id !== boundary.id) {
    if (current.type === "INSTANCE" && current.name === name) return true;
    current = current.parent;
  }
  return false;
}

function requireConsumerModuleHeading(root, heading) {
  const hasHeading = root.findAllWithCriteria({ types: ["TEXT"] })
    .some((textNode) => textNode.name === "label" && textNode.characters === heading);

  if (!hasHeading) {
    throw new Error(`Node '${root.id}' is missing '${heading}' consumer module heading text.`);
  }
}

async function setModuleInstance(moduleInstance, moduleName, mutatedNodeIds) {
  requireModuleVariantProperty(moduleInstance, MODULE_PROPS.name);
  requireModuleVariantProperty(moduleInstance, MODULE_PROPS.size);

  moduleInstance.visible = true;
  moduleInstance.setProperties({
    [MODULE_PROPS.name]: moduleName,
    [MODULE_PROPS.size]: SMALL_MODULE_SIZE,
  });
  mutatedNodeIds.push(moduleInstance.id);
  await updateNamedTextNodes(moduleInstance, "label", [moduleName], mutatedNodeIds);
}

function requireModuleVariantProperty(moduleInstance, propertyName) {
  const property = moduleInstance.componentProperties?.[propertyName];
  if (!property || property.type !== "VARIANT") {
    throw new Error(
      `Expected '${moduleInstance.id}' to be a '${MODULE_INSTANCE_NAME}' instance with '${propertyName}' variant property.`
    );
  }
}

async function loadTextNodeFonts(textNode) {
  const segments = textNode.getStyledTextSegments(["fontName"]);
  const fontKeys = new Set();

  for (const segment of segments) {
    if (segment.fontName === figma.mixed) {
      continue;
    }
    fontKeys.add(`${segment.fontName.family}\u0000${segment.fontName.style}`);
  }

  for (const fontKey of fontKeys) {
    const [family, style] = fontKey.split("\u0000");
    await figma.loadFontAsync({ family, style });
  }
}

function writeMetadata(page, designModel) {
  page.setSharedPluginData(METADATA_NAMESPACE, "schemaVersion", String(designModel.schemaVersion));
  page.setSharedPluginData(METADATA_NAMESPACE, "branch", designModel.branch);
  page.setSharedPluginData(METADATA_NAMESPACE, "gitSha", designModel.gitSha);
  page.setSharedPluginData(METADATA_NAMESPACE, "modelHash", designModel.modelHash);
  page.setSharedPluginData(METADATA_NAMESPACE, "syncedAt", new Date().toISOString());
}

return await main(DESIGN_MODEL);
